"""Constants for the WattPlan integration."""

DOMAIN = "wattplan"

SERVICE_SET_TARGET = "set_target"
SERVICE_RUN_OPTIMIZE_NOW = "run_optimize_now"
SERVICE_RUN_PLAN_NOW = "run_plan_now"
SERVICE_EXPORT_PLANNER_INPUT = "export_planner_input"
SERVICE_EXPORT_USAGE_FORECAST_DEBUG = "export_usage_forecast_debug"
ATTR_BATTERY = "battery"
ATTR_SOC_KWH = "soc_kwh"
ATTR_REACH_AT = "reach_at"
ATTR_ENTRY_ID = "entry_id"

CONF_ACTION_EMISSION_ENABLED = "action_emission_enabled"
CONF_ADAPTER_TYPE = "adapter_type"
CONF_AGGREGATION_MODE = "aggregation_mode"
CONF_CLAMP_MODE = "clamp_mode"
CONF_CONFIG_ENTRY_ID = "config_entry_id"
CONF_BATTERIES = "batteries"
CONF_CAN_CHARGE_FROM_GRID = "can_charge_from_grid"
CONF_CAN_CHARGE_FROM_PV = "can_charge_from_pv"
CONF_CAPACITY_KWH = "capacity_kwh"
CONF_CHARGE_EFFICIENCY = "charge_efficiency"
CONF_COMFORTS = "comforts"
CONF_DURATION_MINUTES = "duration_minutes"
CONF_DISCHARGE_EFFICIENCY = "discharge_efficiency"
CONF_EXPECTED_POWER_KW = "expected_power_kw"
CONF_ENERGY_MODE = "energy_mode"
CONF_ENERGY_PROFILE = "energy_profile"
CONF_ENERGY_USAGE_KWH = "energy_usage_kwh"
CONF_ENERGY_KWH = "energy_kwh"
CONF_HAS_SOLAR = "has_solar"
CONF_HOURS_TO_PLAN = "hours_to_plan"
CONF_MAX_CONSECUTIVE_OFF_MINUTES = "max_consecutive_off_minutes"
CONF_MAX_CHARGE_KW = "max_charge_kw"
CONF_MAX_DISCHARGE_KW = "max_discharge_kw"
CONF_MEASURED_POWER_SOURCE = "measured_power_source"
CONF_MIN_CONSECUTIVE_OFF_MINUTES = "min_consecutive_off_minutes"
CONF_MIN_CONSECUTIVE_ON_MINUTES = "min_consecutive_on_minutes"
CONF_MINIMUM_KWH = "minimum_kwh"
CONF_MIN_OPTION_GAP_MINUTES = "min_option_gap_minutes"
CONF_ON_OFF_SOURCE = "on_off_source"
CONF_ON_HOURS_LAST_WINDOW = "on_hours_last_window"
CONF_OPTIONALS = "optionals"
CONF_OPTIONS_COUNT = "options"
CONF_PLANNING_ENABLED = "planning_enabled"
CONF_ROLLING_WINDOW_HOURS = "rolling_window_hours"
CONF_RUN_WITHIN_HOURS = "run_within_hours"
CONF_RESAMPLE_MODE = "resample_mode"
CONF_SLOT_MINUTES = "slot_minutes"
CONF_SOC_SOURCE = "soc_source"
CONF_SOURCE_MODE = "source_mode"
CONF_SOURCES = "sources"
CONF_SOURCE_PRICE = "price"
CONF_SOURCE_PV = "pv"
CONF_SOURCE_USAGE = "usage"
CONF_HISTORY_DAYS = "history_days"
CONF_TEMPLATE = "template"
CONF_TARGET_ON_HOURS_PER_WINDOW = "target_on_hours_per_window"
CONF_TIME_KEY = "time_key"
CONF_VALUE_KEY = "value_key"
CONF_EDGE_FILL_MODE = "edge_fill_mode"
CONF_FIXUP_PROFILE = "fixup_profile"
CONF_WAS_ON_FOR_MINUTES = "was_on_for_minutes"
CONF_IS_ON_NOW = "is_on_now"

SOURCE_MODE_TEMPLATE = "template"
SOURCE_MODE_ENTITY_ADAPTER = "entity_adapter"
SOURCE_MODE_ENERGY_PROVIDER = "energy_provider"
SOURCE_MODE_BUILT_IN = "built_in"
SOURCE_MODE_NOT_USED = "not_used"

AGGREGATION_MODE_FIRST = "first"
AGGREGATION_MODE_LAST = "last"
AGGREGATION_MODE_MEAN = "mean"
AGGREGATION_MODE_MIN = "min"
AGGREGATION_MODE_MAX = "max"

CLAMP_MODE_NONE = "none"
CLAMP_MODE_NEAREST = "nearest"

RESAMPLE_MODE_NONE = "none"
RESAMPLE_MODE_FORWARD_FILL = "forward_fill"
RESAMPLE_MODE_LINEAR = "linear"

EDGE_FILL_MODE_NONE = "none"
EDGE_FILL_MODE_HOLD = "hold"

FIXUP_PROFILE_STRICT = "strict_input"
FIXUP_PROFILE_REPAIR = "repair_gaps"
FIXUP_PROFILE_EXTEND = "extend_daily_pattern"

ADAPTER_TYPE_ATTRIBUTE_OBJECTS = "attribute_objects"
ADAPTER_TYPE_ATTRIBUTE_VALUES = "attribute_values"

ENERGY_MODE_SCALAR = "scalar"
ENERGY_MODE_PROFILE = "profile"

SLOT_MINUTE_OPTIONS: tuple[int, ...] = (15, 30, 60)
HOURS_TO_PLAN_OPTIONS: tuple[int, ...] = (12, 24, 48, 72, 96, 120, 144, 168)

SUBENTRY_TYPE_BATTERY = "battery"
SUBENTRY_TYPE_COMFORT = "comfort"
SUBENTRY_TYPE_OPTIONAL = "optional"
